### SUC CREATE TASK
POST http://localhost:8080/api/task
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "title": "hello world",
  "content": "hahahoho",
  "assignee": "helloworld"
}

### SUC CREATE TASK
POST http://localhost:8080/api/task
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "content": "hahahoho"
}


### SUC CREATE TASK WITHOUT ASSIGNEE
POST http://localhost:8080/api/task
Content-Type: application/json

{
  "title": "hello world",
  "content": "hahahoho",
  "password": "1234"
}

### SUC CREATE TASK WITHOUT CONTENT
POST http://localhost:8080/api/task
Content-Type: application/json

{
  "title": "hello world",
  "assignee": "hello",
  "password": "1234"
}

### FIND BY ID
GET localhost:8080/api/task/6

### test
GET localhost:8080/api/task/test

### SHOW ALL
GET localhost:8080/api/task
Authorization: Bearer {{access_token}}

### UPDATE
PUT localhost:8080/api/task/1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "title": "title is updated22",
  "content": "content is updated"
}

### DELETE
DELETE localhost:8080/api/task/1
Authorization: Bearer {{access_token}}
