### SUC CREATE TASK
POST http://localhost:8080/api/task
Content-Type: application/json

{
  "title": "hello world",
  "content": "hahahoho",
  "assignee": "foo",
  "password": "1234"
}

### SUC CREATE TASK WITHOUT ASSIGNEE
POST http://localhost:8080/api/task
Content-Type: application/json

{
  "title": "hello world",
  "content": "hahahoho",
  "password": "1234"
}

### SUC CREATE TASK WITHOUT CONTENT
POST http://localhost:8080/api/task
Content-Type: application/json

{
  "title": "hello world",
  "assignee": "hello",
  "password": "1234"
}

### FIND BY ID
GET localhost:8080/api/task/10

### SHOW ALL
GET localhost:8080/api/task

### UPDATE
PUT localhost:8080/api/task/10
Content-Type: application/json

{
  "title": "title is updated",
  "content": "content is updated",
  "password": "1234"
}

### DELETE
DELETE localhost:8080/api/task/11
Content-Type: application/json

{
  "password": "1234"
}

