### signup

POST localhost:8080/api/user
Content-Type: application/json

{
  "username": "helloworld",
  "nickname": "thisisnickname",
  "password": "helloworld"
}

### signup 2

POST localhost:8080/api/user
Content-Type: application/json

{
  "username": "foobar",
  "nickname": "foobar",
  "password": "password"
}
### signup admin

POST localhost:8080/api/user
Content-Type: application/json

{
  "username": "admin",
  "nickname": "admin",
  "password": "password"
}
